pip3 install --force-reinstall jsonschema==2.6.0
pip3 install --force-reinstall numpy==1.17.2
pip3 install --force-reinstall simplejson==3.16.0
pip3 install --force-reinstall klein==17.10.0
pip3 install --force-reinstall ruamel.yaml==0.15.100
pip3 install --force-reinstall scikit-learn==0.20.4
pip3 install --force-reinstall typing==3.7.4.1
pip3 install --force-reinstall coloredlogs==10.0
pip3 install --force-reinstall tqdm==4.36.1
pip3 install --force-reinstall requests==2.22.0
pip3 install --force-reinstall boto3==1.9.246
pip3 install --force-reinstall gevent==1.4.0
pip3 install --force-reinstall matplotlib==2.2.4
pip3 install --force-reinstall cloudpickle==0.6.1
pip3 install --force-reinstall packaging==18.0
pip3 install --force-reinstall jsonschema==2.6.0
pip3 install --force-reinstall simplejson==3.16.0
pip3 install --force-reinstall klein==17.10.0
pip3 install --force-reinstall ruamel.yaml==0.15.100
pip3 install --force-reinstall scikit-learn==0.20.4
pip3 install --force-reinstall typing==3.7.4.1
pip3 install --force-reinstall future==0.17.1
pip3 install --force-reinstall coloredlogs==10.0
pip3 install --force-reinstall tqdm==4.36.1
pip3 install --force-reinstall requests==2.22.0
pip3 install --force-reinstall boto3==1.9.246
pip3 install --force-reinstall gevent==1.4.0
pip3 install --force-reinstall matplotlib==2.2.4
pip3 install --force-reinstall cloudpickle==0.6.1
pip3 install --force-reinstall packaging==18.0
pip3 install --force-reinstall pika==0.12.0
pip3 install --force-reinstall colorhash==1.0.2
pip3 install --force-reinstall tqdm==4.36.1
pip3 install --force-reinstall fbmessenger==5.6.0
pip3 install --force-reinstall networkx==2.3
pip3 install --force-reinstall terminaltables==3.1.0
pip3 install --force-reinstall jsonschema==2.6.0
pip3 install --force-reinstall scikit-learn==0.20.4
pip3 install --force-reinstall packaging==18.0
pip3 install --force-reinstall pykwalify==1.7.0
pip3 install --force-reinstall jsonpickle==1.2
pip3 install --force-reinstall rocketchat-API==0.6.34
pip3 install --force-reinstall python-dateutil==2.8.0
pip3 install --force-reinstall typing==3.7.4.1
pip3 install --force-reinstall fakeredis==0.10.3
pip3 install --force-reinstall mattermostwrapper==2.1
pip3 install --force-reinstall Flask-Cors==3.0.8
pip3 install --force-reinstall pymongo==3.9.0
pip3 install --force-reinstall pytz==2018.9
pip3 install --force-reinstall ruamel.yaml==0.15.100
pip3 install --force-reinstall Flask==1.1.1
pip3 install --force-reinstall APScheduler==3.6.1
pip3 install --force-reinstall twilio==6.31.1
pip3 install --force-reinstall webexteamssdk==1.2
pip3 install --force-reinstall tensorflow==1.13.2
pip3 install --force-reinstall Flask-JWT-Simple==0.0.3
pip3 install --force-reinstall scipy==1.3.1
pip3 install --force-reinstall redis==2.10.6
pip3 install --force-reinstall python-telegram-bot==11.1.0
pip3 install --force-reinstall colorclass==2.2.0
pip3 install --force-reinstall pydot==1.4.1
pip3 install --force-reinstall questionary==1.3.0
pip3 install --force-reinstall python-socketio==3.1.2
pip3 install --force-reinstall requests==2.22.0
pip3 install --force-reinstall gevent==1.4.0
pip3 install --force-reinstall slackclient==1.3.2
pip3 install --force-reinstall coloredlogs==10.0
pip3 install --force-reinstall rasa-nlu==0.15.1
pip3 install --force-reinstall rasa-core==0.14.5
pip3 install --force-reinstall rasa-core-sdk==0.14.0
pip3 install --force-reinstall spacy==2.0.18
pip3 install --force-reinstall tornado==6.0.3
