slots:
  location:
    type: text
  cuisine:
    type: text
  budget:
    type: text
  email:
    type: text
  city_status:
    type: categorical
    values:
    - Service
    - No_Service
    - Invalid

entities:
- location
- cuisine
- budget
- email
- city_status

intents:
 - affirm
 - deny
 - restaurant_search
 - send_email
 - greet
 - goodbye
 - location
 - cuisine

actions:
- action_validate_city
- action_restaurant
- action_send_email
- action_restart_conversation
- utter_greet
- utter_goodbye
- utter_default
- utter_ask_howcanhelp
- utter_ask_location
- utter_ask_cuisine
- utter_ask_price_range
- utter_ask_for_email_to_send
- utter_sorry_dont_operate
- utter_location_not_found
- utter_searching
- utter_ask_email_address
- utter_email_sent
- utter_no_email_sent

templates:
  utter_greet:
    - "Hey there! Kindly let me now how may I help you ?"
    - "Hi, Please tell me how can I help you!"
    - "Hey, How is it going. How May I help you Today"
    - "Namaste , How May I help you Today"
  utter_goodbye:
    - "goodbye :("
    - "Bye-bye"
  utter_default:
    - "Please enter proper query."
  utter_ask_cuisine: 
    - text: "What kind of cuisine would you like?"
      buttons:
      - title: "Chinese"
        payload: "Chinese"
      - title: "Mexican"
        payload: "Mexican"
      - title: "Italian"
        payload: "Italian"
      - title: "American"
        payload: "American"
      - title: "South Indian"
        payload: "South Indian"
      - title: "North Indian"
        payload: "North Indian"
  utter_ask_howcanhelp:
    - "how can I help you?"
  utter_ask_location:
    - "In what location ?"
  utter_ask_price_range:
    - text: "What price range are you looking at?"
      buttons:
      - title: "Lesser than Rs. 300"
        payload: "<300"
      - title: "Rs. 300 to 700"
        payload: "300-700"
      - title: "More than 700"
        payload: ">700"
  utter_sorry_dont_operate:
    - "Sorry, we don’t operate in this city. Can you please specify some other location ? \n"
  utter_location_not_found:
    - "Sorry, didn’t find any such location. Can you please tell again? \n"
  utter_searching:
    - "Ok, let me find some good rating restaurants for your budget range... \n"
  utter_ask_for_email_to_send:
    - "Should I send you details of all the restaurants on email ? \n"
  utter_ask_email_address:
    - "To what email id should I send it to ? \n"
  utter_email_sent:
    - "Sent. Bon Appetit!"
  utter_no_email_sent:
    - "Okay! Bon Appetit!"
